# task setup
task: ner
zero_shot_transfer: False
transfer_source: None
langs: ['hy', 'eu', 'myv', 'et', 'he', 'ru', 'te']
dataset_path: data/ner-mono
# whether to start with a randomly-initialized model
random_weights: False

# model options
model_class: xlmr
model_name: models/multi_mrl/cpt_emb-32k-script+ident/best-checkpoint
tokenizer_path: tokenizers/multi_mrl_spm_32k.model
checkpoint_path: models/multi_mrl/ner/xlmr_cpt_emb-32k-script+ident

# training options
random_seed: 1
epochs: 32
batch_size: 72
gradient_accumulation: 1
max_seq_length: 256
max_train_examples: 32768
# checkpoints every two epochs, so patience epochs is this parameter x2
patience: 2
