# datasets
train_dataset_path: data/multilingual/multi_mrl_train_alpha02_20mil
sharded_train_dataset: True
val_dataset_path: data/multilingual/multi_mrl_dev_alpha02.txt
mlm_masking_prob: 0.15
max_seq_len: 256

# training
seed: 1
hf_model: xlm-roberta-base
learning_rate: 1e-5
training_epochs: 1
train_batch_size: 25
gradient_accumulation_steps: 8
logging_steps: 250
eval_strategy: steps
eval_steps: 1000
eval_batch_size: 100
checkpoints_directory: models/multi_mrl/cpt_emb-32k-script+pos
save_steps: 1000
saved_checkpoints_limit: 2
load_best_model_at_end: True

# advanced training options
new_vocab_file: tokenizers/multi_mrl_spm_32k.model
new_embedding_path: tokenizers/multi_mrl_emb_32k_script+position.pt
freeze_main_model: True
model_freeze_prefix: "roberta.encoder"
weight_decay: 0.0
lr_scheduler_type: "linear"
warmup_ratio: 0.0
warmup_steps: 0.0 # overrides warmup ratio
auto_find_batch_size: False # requires accelerate library
group_by_length: False # reduce padding effect
gradient_checkpointing: False
fp16: False # mixed precision training
torch_distributed_training: False # fsdp parameter in HF code
full_determinism: False # ensure reproducible results in distributed training
