# task setup
task: pos
zero_shot_transfer: False
transfer_source: None
langs: ['myv', 'sme', 'et', 'fi', 'hu']
# might sometimes need to break the list in half if there's risk of the node being pre-empted
# langs: ['myv', 'sme', 'et', 'hu']
# langs: ['fi']
dataset_path: data/ud-uralic
# whether to start with a randomly-initialized model
random_weights: False

# model options
model_class: xlmr
model_name: xlm-roberta-base
checkpoint_path: models/uralic/pos/full_train/xlmr_ots

# training options
random_seed: 1
epochs: 64
batch_size: 36
gradient_accumulation: 2
max_train_examples: null
# checkpoints every two epochs, so patience epochs is this parameter x2
patience: 4
