# datasets
train_dataset_path: "data/multilingual/caucasus_train"
sharded_train_dataset: True
val_dataset_path: "data/multilingual/multiling_sampled_04_5mil_val.txt"
mlm_masking_prob: 0.15
max_seq_len: 128

# training
seed: 1
hf_model: "xlm-roberta-base"
learning_rate: 5e-5
training_epochs: 1
train_batch_size: 384
gradient_accumulation_steps: 1
eval_strategy: "steps"
eval_steps: 1024
eval_batch_size: 384
checkpoints_directory: "./checkpoints"
save_steps: 1024
saved_checkpoints_limit: 4

# advanced training options
new_vocab_file: tokenizers/caucasus_spm.model
freeze_main_model: True
model_freeze_prefix: "roberta.encoder"
weight_decay: 0.0
lr_scheduler_type: "linear"
warmup_ratio: 0.0
warmup_steps: 0.0 # overrides warmup ratio
auto_find_batch_size: False # requires accelerate library
group_by_length: False # reduce padding effect
gradient_checkpointing: False
fp16: False # mixed precision training
torch_distributed_training: False # fsdp parameter in HF code
full_determinism: False # ensure reproducible results in distributed training
