# task setup
task: pos
zero_shot_transfer: True
transfer_source: myv
langs: [kpv]
dataset_path: data/ud-uralic
# whether to start with a randomly-initialized model
random_weights: False

# model options
model_class: xlmr
model_name: models/komi/lapt_emb16k_budgeted-400k/best-checkpoint
tokenizer_path: tokenizers/komi_spm_16k.model
checkpoint_path: models/komi/pos/zero-shot/xlmr_lapt_mono_emb16k_budgeted-400k

# training options
random_seed: 1
epochs: 64
batch_size: 36
gradient_accumulation: 2
max_train_examples: null
# checkpoints every two epochs, so patience epochs is this parameter x2
patience: 4
