# task setup
task: pos
zero_shot_transfer: False
transfer_source: None
langs: ['hy', 'eu', 'myv', 'et', 'he', 'ru', 'sme', 'te']
dataset_path: data/ud-mono
# whether to start with a randomly-initialized model
random_weights: False

# model options
model_class: xlmr
model_name: models/multi_mrl/cpt-full_emb-32k/best-checkpoint
tokenizer_path: tokenizers/multi_mrl_spm_32k.model
checkpoint_path: models/multi_mrl/pos/xlmr_cpt-full_emb-32k

# training options
random_seed: 1
epochs: 64
batch_size: 72
gradient_accumulation: 1
max_seq_length: 256
max_train_examples: 32768
# checkpoints every two epochs, so patience epochs is this parameter x2
patience: 4
