# task setup
task: pos
zero_shot_transfer: True
transfer_source: uralic
langs: [kpv, krl, mdf, olo, sms]
dataset_path: data/ud-uralic
# whether to start with a randomly-initialized model
random_weights: False

# model options
model_class: xlmr
model_name: models/uralic/cpt_emb-32k-script+pos+ident/checkpoint-90000
tokenizer_path: tokenizers/uralic_spm_32k.model
checkpoint_path: ./models/uralic/pos/zero_shot/xlmr_cpt_emb-32k-script+pos+ident

# training options
random_seed: 1
epochs: 64
batch_size: 36
gradient_accumulation: 2
max_train_examples: null
# checkpoints every two epochs, so patience epochs is this parameter x2
patience: 4
