# task setup
task: pos
zero_shot_transfer: False
transfer_source: None
langs: ['myv', 'sme', 'et', 'fi', 'hu', 'no', 'ru']
dataset_path: data/ud-uralic
# whether to start with a randomly-initialized model
random_weights: False

# model options
model_class: xlmr
model_name: xlm-roberta-base
checkpoint_path: ./models/uralic/pos/full_train/xlmr_ots

# training options
random_seed: 1
epochs: 64
batch_size: 72
max_train_examples: null
# checkpoints every two epochs, so patience epochs is this parameter x2
patience: 4
