# Sentencepiece vocabulary parameters
tokenizer_model: unigram
vocab_size: 16384
train_dataset_path: data/multilingual/uralic_vocab_train_alpha02_5mil.txt
output_path: tokenizers/uralic_spm_16k

# Paths and alpha for sampling vocab training set
alpha: 0.2
output_length: 5000000
combined_data_output: data/multilingual/uralic_vocab_train_alpha02_5mil.txt
data_files:
    russian:
        directory: data/indo-european/russian/ru_oscar_cleaned
        files: [ru_oscar_cleaned_shard1.txt, ru_oscar_cleaned_shard2.txt,
            ru_oscar_cleaned_shard3.txt, ru_oscar_cleaned_shard4.txt, ru_oscar_cleaned_shard5.txt,
            ru_oscar_cleaned_shard6.txt, ru_oscar_cleaned_shard7.txt, ru_oscar_cleaned_shard8.txt,
            ru_oscar_cleaned_shard9.txt, ru_oscar_cleaned_shard10.txt]
    hungarian:
        directory: data/uralic/hungarian/hu_oscar_cleaned
        files: [hu_oscar_cleaned_shard1.txt, hu_oscar_cleaned_shard2.txt,
            hu_oscar_cleaned_shard3.txt, hu_oscar_cleaned_shard4.txt]
    finnish:
        directory: data/uralic/finnish/fi_oscar_cleaned
        files: [fi_oscar_cleaned_shard1.txt, fi_oscar_cleaned_shard2.txt,
            fi_oscar_cleaned_shard3.txt, fi_oscar_cleaned_shard4.txt]
    estonian:
        directory: data/uralic/estonian/et_oscar_cleaned
        files: [et_oscar_cleaned_shard1.txt, et_oscar_cleaned_shard2.txt, 
            et_oscar_cleaned_shard3.txt, et_oscar_cleaned_shard4.txt, et_oscar_cleaned_shard5.txt,
            et_oscar_cleaned_shard6.txt, et_oscar_cleaned_shard7.txt, et_oscar_cleaned_shard8.txt,
            et_oscar_cleaned_shard9.txt, et_oscar_cleaned_shard10.txt]
    erzya:
        directory: data/uralic/erzya
        files: [myv_combined_cleaned.txt]
    komi:
        directory: data/uralic/komi
        files: [koi_combined_cleaned.txt]
    mari:
        directory: data/uralic/mari
        files: [mhr_combined_cleaned.txt]
    moksha:
        directory: data/uralic/moksha
        files: [mdf_combined_cleaned.txt]
    north_finnic:
        directory: data/uralic/north_finnic
        files: [ingrian/izh_combined_cleaned.txt, karelian/krl_combined_cleaned_train.txt,
            livonian/liv_combined_cleaned_train.txt, veps/vep_combined_cleaned_train.txt,
            votic/vot_combined_cleaned.txt]
    sami:
        directory: data/uralic/sami
        files: [sami_combined_cleaned.txt]
    udmurt:
        directory: data/uralic/udmurt
        files: [udm_combined_cleaned.txt]
