# task setup
task: pos
zero_shot_transfer: True
transfer_source: uralic
langs: [kpv, krl, mdf, olo, sms]
dataset_path: data/ud-uralic
# whether to start with a randomly-initialized model
random_weights: False

# model options
model_class: xlmr
model_name: xlm-roberta-base
checkpoint_path: ./models/uralic/pos/zero_shot/xlmr_ots

# training options
random_seed: 1
epochs: 64
batch_size: 72
max_train_examples: null
