# task setup
task: pos
zero_shot_transfer: False
transfer_source: None
langs: ['myv', 'sme', 'et', 'fi', 'hu', 'ru']
dataset_path: data/ud-uralic
# whether to start with a randomly-initialized model
random_weights: False

# model options
model_class: xlmr
model_name: models/uralic/cpt_embed_32k/checkpoint-200000
tokenizer_path: tokenizers/uralic_spm_32k.model
checkpoint_path: ./models/uralic/pos/equal_train/xlmr_embed_32k

# training options
random_seed: 1
epochs: 64
batch_size: 72
max_train_examples: 896
