# task setup
task: uas
zero_shot_transfer: False
transfer_source: None
langs: ['myv', 'sme', 'et', 'fi', 'hu', 'ru']
dataset_path: data/ud-uralic
# whether to start with a randomly-initialized model
random_weights: False

# model options
model_class: xlmr
model_name: models/uralic_mrl/cpt-full_emb-32k-focus/best-checkpoint
tokenizer_path: tokenizers/uralic_mrl_spm_32k.model
checkpoint_path: models/uralic_mrl/pos/xlmr_cpt-full_emb-32k-focus

# training options
random_seed: 1
epochs: 64
batch_size: 72
gradient_accumulation: 1
max_seq_length: 256
max_train_examples: 512
# checkpoints every two epochs, so patience epochs is this parameter x2
patience: 4
